server:
  port: 8082
spring:
  application:
    name: jpa-demo
  #配置rabbitMq 服务器
  rabbitmq:
    #设置RabbitMQ的IP地址
    host: 127.0.0.1
    #设置rabbitmq服务器连接端口
    port: 5672
    #设置rabbitmq服务器用户名  本地搭建对应的账户密码都是 guest
    username: guest
    #设置rabbitmq服务器密码
    password: guest
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpa_demo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    password: 1qaz@WSX
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 20000
  jpa:
    # 是否打印sql
    show-sql: false
    hibernate:
      # 开启自动建表功能，一般选update，每次启动会对比实体和数据表结构是否相同，不相同会更新
      ddl-auto: update
    # 设置创表引擎为Innodb，不然默认为MyiSam
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect